services:
  # ------------------------------------------------------------------------------------------
  # -----------------------------------------------------------------------
  # ---------------------- Main

  main:
    build: .
    container_name: fintechapp
    volumes:
      - ./app/src:/app/src
      - ./app/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
    # environment:
    #   - DOCKER_HOST=unix:///var/run/docker.sock # Set Docker host
    ports:
      - 8050:8050
    depends_on:
      - pgdatabase
    restart: "on-failure"

  # ------------------------------------------------------------------------------------------
  # -----------------------------------------------------------------------
  # ---------------------- Postgres

  pgdatabase:
    image: postgres:13
    container_name: pgdatabase_m4
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fintechdb
    ports:
      - 5432:5432
    volumes:
      - ./app/volumes/data_postgres:/var/lib/postgresql/data

  # ------------------------------------------------------------------------------------------
  # -----------------------------------------------------------------------
  # ---------------------- pgAdmin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_m4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8090:80
    depends_on:
      - pgdatabase
    restart: on-failure

    volumes:
      - ./app/volumes/data_pgadmin:/var/lib/pgadmin
      - ./app/volumes/data_pgadmin/sessions:/var/lib/pgadmin/sessions

  # ------------------------------------------------------------------------------------------
  # -----------------------------------------------------------------------
  # ----------------------
